# Application Configuration
application:
  name: DevOpsSimulator
  version: 2.0.0-beta
  environment: production  # switched to production mode for deployment

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # hot_reload: true  # only used in development

logging:
  level: INFO
  format: json
  output: /var/log/app.log
  # show_stack_trace: true  # uncomment for debugging

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # experimental_features: true  # only for dev/testing

# Development-only settings (disabled in production)
# development:
#   mock_external_apis: true
#   debug_mode: true
#   cors_enabled: true
#
# notifications:
#   slack_webhook: "https://hooks.slack.com/services/XXX"
#   discord_webhook: "https://discord.com/api/webhooks/YYY"
#   email_alerts: false
